In [1]:
# pip install numpy
# conda install numpy
import numpy as np

In [2]:
arreglo_np_list = np.array( [1,2,3] )
arreglo_np_list

array([1, 2, 3])

In [3]:
arreglo_np_tupla = np.array( (1,2,3) )
arreglo_np_tupla

array([1, 2, 3])

In [4]:
print(type(arreglo_np_list))
print(type(arreglo_np_tupla))
print(arreglo_np_list)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [10]:
np.ones(4) # [1, 1, 1, 1]

array([1., 1., 1., 1.])

In [6]:
np.ones(10000)

array([1., 1., 1., ..., 1., 1., 1.])

In [7]:
np.zeros(1)

array([0.])

In [9]:
np.zeros(5000)

array([0., 0., 0., ..., 0., 0., 0.])

In [12]:
uno = np.ones(1)
uno

array([1.])

In [14]:
print(type(uno[0]))

<class 'numpy.float64'>


In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.ones([3, 2])
# [[1,1],[1,1],[1,1]]

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.ones((2, 3, 4)).shape

(2, 3, 4)

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(-20, -10) # [-20, -10[

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [28]:
np.arange(30,66) # [30, 66[

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65])

In [29]:
np.arange(-20, -10 , 5) # [-20, -10[ en saltos de 5 en 5

array([-20, -15])

In [30]:
np.arange(-20, -10, 2)

array([-20, -18, -16, -14, -12])

In [31]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [32]:
np.arange(3, 5 ,0.1).shape

(20,)

In [36]:
np.arange(3, 5 ,0.1).reshape(5, 2, 2)
np.arange(3, 5 ,0.1).reshape(10, 2)
np.arange(3, 5 ,0.1).reshape(2, 10)
np.arange(3, 5 ,0.1).reshape(2, 5, 2)

array([[[3. , 3.1],
        [3.2, 3.3],
        [3.4, 3.5],
        [3.6, 3.7],
        [3.8, 3.9]],

       [[4. , 4.1],
        [4.2, 4.3],
        [4.4, 4.5],
        [4.6, 4.7],
        [4.8, 4.9]]])

In [38]:
np.arange(3, 5 ,0.1).reshape(2, 5, 2).flatten()

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [39]:
np.arange(3, 5 ,0.1).reshape(2, 5, 2).flatten().shape

(20,)

In [50]:
np.random.randint(0, 10, 5) # [0, 10[ 5 randomicos

array([3, 8, 1, 8, 1])

In [51]:
np.random.rand(6)

array([0.24913093, 0.52261136, 0.26424792, 0.3074647 , 0.557616  ,
       0.06739862])

In [52]:
a = np.array( [
    [1, 2],
    [3, 4]
] )
b = np.array( [
    [5, 6],
    [7, 8]
] )
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [53]:
# Suma 
a + b

array([[ 6,  8],
       [10, 12]])

In [54]:
# Resta 
a - b

array([[-4, -4],
       [-4, -4]])

In [55]:
# Multiplicacion
a * b

array([[ 5, 12],
       [21, 32]])

In [56]:
# Division
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [57]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [58]:
a % 2

array([[1, 0],
       [1, 0]])

In [59]:
a + 10

array([[11, 12],
       [13, 14]])

In [60]:
(a * 2) / 5 * 100

array([[ 40.,  80.],
       [120., 160.]])

In [61]:
a < 2

array([[ True, False],
       [False, False]])

In [64]:
a < b

array([[ True,  True],
       [ True,  True]])

In [67]:
a[a < 4]

array([1, 2, 3])

In [68]:
b[b < 7]

array([5, 6])

In [69]:
a += 2 # a = a + 2 

In [70]:
a

array([[3, 4],
       [5, 6]])

In [71]:
a *= 2 # a = a * 2

In [72]:
a

array([[ 6,  8],
       [10, 12]])

In [73]:
arreglo = np.arange(1,11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arreglo.sum()

55

In [ ]:
arreglo.min()

In [ ]:
arreglo.max()

In [75]:
matriz = np.arange(12).reshape(3,4)

In [76]:
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
matriz.sum()

66

In [78]:
matriz.sum(axis = 0)

array([12, 15, 18, 21])

In [79]:
matriz.sum(axis = 1)

array([ 6, 22, 38])

In [81]:
notas = np.array([1,2,3,5,3,2,7,8,5,3,2,9,7,6])

In [82]:
notas.mean()

4.5

In [83]:
np.median(notas)

4.0

In [84]:
np.std(notas)

2.471263413143742

In [85]:
np.var(notas)

6.107142857142857

In [86]:
path = "./05_salarios.csv"
salarios = np.genfromtxt(path, delimiter = ',')

In [87]:
salarios

array([1., 2., 4., 6., 4., 3., 2., 1., 5., 6., 7., 9., 9., 7., 5., 4., 5.,
       4., 2., 1., 5., 6., 7., 9., 0., 7., 6., 4., 3., 2., 1., 5.])

In [88]:
salarios.mean()

4.4375

In [89]:
once = np.arange(11)**2

In [90]:
once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
once[::2]

array([  0,   4,  16,  36,  64, 100])

In [92]:
once[::3]

array([ 0,  9, 36, 81])

In [93]:
once[::5]

array([  0,  25, 100])

In [94]:
arreglo_split = np.arange(15)
np.split(arreglo_split, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [95]:
arreglo_split

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
np.split(arreglo_split, [2, 6, 9, 13])

[array([0, 1]),
 array([2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14])]

In [97]:
salarios

array([1., 2., 4., 6., 4., 3., 2., 1., 5., 6., 7., 9., 9., 7., 5., 4., 5.,
       4., 2., 1., 5., 6., 7., 9., 0., 7., 6., 4., 3., 2., 1., 5.])

In [99]:
print(salarios.sort())
print(salarios)

None
[0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 6. 6. 6.
 6. 7. 7. 7. 7. 9. 9. 9.]


In [100]:
salarios[::-1].sort()
print(salarios)

[9. 9. 9. 7. 7. 7. 7. 6. 6. 6. 6. 5. 5. 5. 5. 5. 4. 4. 4. 4. 4. 3. 3. 2.
 2. 2. 2. 1. 1. 1. 1. 0.]
